version: '3.5'

services:
    preview-php-cli:
        build:
            context: ./php-cli
        environment:
            - APP_ENV=${APP_ENV}
            - APP_SECRET=${APP_SECRET}
        volumes:
            - ../:/app

    preview-php-fpm:
        build:
            context: ./php-fpm
        environment:
            - APP_ENV=${APP_ENV}
            - APP_SECRET=${APP_SECRET}
        volumes:
            - ../:/app

    preview-nginx:
        build:
            context: ./nginx
        volumes:
            - ../:/app
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/sites/:/etc/nginx/sites-available
            - ./nginx/conf.d/:/etc/nginx/conf.d
            - ./logs:/var/log
        depends_on:
            - preview-php-fpm
            - preview-database
        ports:
            - "${NGINX_PORT}:80"

    preview-database:
        build:
            context: ./mysql
        volumes:
            - preview.mysql.data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - "${MYSQL_PORT}:3306"

    preview-node-cli:
        tty: true
        build:
            context: ./node-cli
        volumes:
            - ../:/app
#
    preview-ssh-server:
        build:
            context: ./ssh-server
        volumes:
            - ../:/app
            - ./ssh-server/sshd_config:/etc/ssh/sshd_config


volumes:
    preview.mysql.data:
networks:
    default:
        name: common
